name: Android and iOS Emulator Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          java-package: 'jdk'
          jdkFile: 'jdk8u144'

      - name: Set up Android SDK
        run: |
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
          unzip -q android-sdk.zip -d $HOME/android-sdk
          echo 'export ANDROID_HOME=$HOME/android-sdk' >> $HOME/.bashrc
          echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools' >> $HOME/.bashrc
          echo 'yes' | $HOME/android-sdk/tools/bin/sdkmanager --licenses
          
      - name: Install JAXB
        run: |
          sudo apt-get update
          sudo apt-get install -y libjaxb-api-java libjaxb-java
          
      - name: Create and start Android emulator
        run: |
          # Aqui você pode adicionar os comandos para criar e iniciar o emulador Android
          
      - name: Run Android tests
        run: |
          ./gradlew test
          
      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-select: 'latest'
          
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          
      - name: Install dependencies
        run: |
          cd ios
          pod install
          
      - name: Run iOS tests
        run: |
          cd ios
          xcodebuild test -scheme YourSchemeName -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.0'
